theme: jekyll-theme-minimal
title: Conversations
description: Writing down the links, books, topics and resources that come up in conversation.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"