theme: jekyll-theme-minimal
title: Conversations
description: Capturing the links, books, topics and resources mentioned in the conversations I have with people
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"